repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    # - id: no-commit-to-branch # Prevent committing to main / master
    - id: check-added-large-files # Check for large files added to git
    - id: check-merge-conflict # Check for files that contain merge conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
