repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args: [--unsafe, --allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/jshwi/docsig
    rev: v0.65.0
    hooks:
      - id: docsig
        args:
          - --ignore-no-params
          - --check-dunders
          - --check-overridden
          - --check-protected
          - --check-class
          - --disable=E113

ci:
  autoupdate_schedule: monthly
