[project]
name = "mch-anemoi-plugins"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MeteoSwiss" }
]
requires-python = ">=3.12"
dependencies = [
    "anemoi-datasets",
    "anemoi-plugins",
    "anemoi-transform",
]


[project.optional-dependencies]
grib = [
    "eccodes>=2.40.0",
    "meteodatalab",
]

[project.scripts]
mch-anemoi-plugins = "mch_anemoi_plugins:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
anemoi-plugins = { git = "https://github.com/ecmwf/anemoi-plugins" }
anemoi-datasets = { git = "https://github.com/ecmwf/anemoi-datasets" }
anemoi-transform = { git = "https://github.com/ecmwf/anemoi-transform" }
meteodatalab = { git = "https://github.com/MeteoSwiss/meteodata-lab", branch = "updated-dependencies"}

[dependency-groups]
dev = [
    "ipdb",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
]

[project.entry-points."anemoi.transform.filters"]
example = "mch_anemoi_plugins.transform.filter:ExamplePlugin"
