[project]
name = "mch-anemoi-plugins"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MeteoSwiss" }
]
requires-python = ">=3.12"
dependencies = [
    "anemoi-datasets",
    "anemoi-plugins",
    "anemoi-transform",
    "meteodatalab",
]

[project.scripts]
mch-anemoi-plugins = "mch_anemoi_plugins:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
anemoi-plugins = { git = "https://github.com/ecmwf/anemoi-plugins" }
anemoi-datasets = { git = "https://github.com/ecmwf/anemoi-datasets" }
anemoi-transform = { git = "https://github.com/ecmwf/anemoi-transform" }
meteodatalab = { git = "https://github.com/MeteoSwiss/meteodata-lab" }

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
]
